-- Phase 4.3.1 — Projects table + captures schema additions
-- See UI-REDESIGN-SPEC.md §15 (data model), §8 (lifecycle states & graduation).
--
-- This migration:
--   1. Adds a `projects` table — capture-anchored, but with explicit "+ New project"
--      also allowed (seed_capture_id is nullable).
--   2. Adds new columns to `captures`: project_id, is_project, suggested_project_id,
--      suggested_project_confidence, source_url, media_kind.
--   3. Drops 'serious' from the captures.state CHECK constraint. Existing serious
--      captures (if any) are migrated to 'developed' — projects are the new
--      graduation, but per Slice A we don't auto-create projects from them; the
--      owner can promote any 'developed' capture to a project in Slice B (4.3.2).
--   4. Enables RLS on projects with the same owner-pattern used for captures.
--
-- ROLLBACK (run in reverse order):
--   alter table public.captures drop column if exists media_kind;
--   alter table public.captures drop column if exists source_url;
--   alter table public.captures drop column if exists suggested_project_confidence;
--   alter table public.captures drop column if exists suggested_project_id;
--   alter table public.captures drop column if exists is_project;
--   alter table public.captures drop column if exists project_id;
--   -- Restoring 'serious' to the CHECK constraint (not actually rolling back the
--   -- state UPDATE; serious captures stay 'developed'):
--   alter table public.captures drop constraint captures_state_check;
--   alter table public.captures add constraint captures_state_check
--     check (state in ('raw','developed','serious','archived'));
--   drop policy if exists projects_owner on public.projects;
--   drop table if exists public.projects;

-- ============================================================
-- 1. projects table
-- ============================================================

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.users(id) on delete cascade,
  seed_capture_id uuid references public.captures(id) on delete set null,
  -- slug is unique per owner; generated by the server action from title at create
  slug text not null,
  title text not null,
  deck text,
  -- kind_seed mirrors the originating capture's kind. Drives the cover gradient
  -- defaults (idea→ember/copper, research→gold, problem→moss, observation→plum).
  kind_seed text check (kind_seed in ('problem','idea','observation','research')),
  cover_kind text not null default 'gradient' check (cover_kind in ('gradient','photo')),
  cover_gradient_key text,                     -- 'ember' | 'gold' | 'moss' | 'plum' | etc; falls back to kind_seed
  cover_photo_path text,                        -- when cover_kind='photo', points to storage object
  stage text,                                   -- free-form for now; UI suggests a few values
  status text not null default 'active' check (status in ('active','archived','wrapped','paused')),
  -- generic word for the inner-list label across project types — per spec §5
  parts_kind text not null default 'parts',
  opened_at timestamptz not null default now(),
  target_at timestamptz,
  progress_pct numeric(5,2),                    -- 0.00 to 100.00
  last_activity_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,                       -- soft-delete; 30-day Trash window applies
  -- one slug per owner (ignoring soft-deleted rows)
  constraint projects_slug_per_owner unique (owner_id, slug)
);

create index projects_owner_status_idx on public.projects (owner_id, status);
create index projects_owner_last_activity_idx on public.projects (owner_id, last_activity_at desc);
create index projects_seed_capture_idx on public.projects (seed_capture_id) where seed_capture_id is not null;

-- ============================================================
-- 2. captures additions
-- ============================================================

alter table public.captures
  add column project_id uuid references public.projects(id) on delete set null,
  add column is_project boolean not null default false,
  add column suggested_project_id uuid references public.projects(id) on delete set null,
  add column suggested_project_confidence numeric(4,3),  -- 0.000 to 1.000
  add column source_url text,                            -- present iff captured as a Web clip
  add column media_kind text not null default 'note' check (media_kind in ('note','voice','photo','clip'));

create index captures_project_idx on public.captures (project_id) where project_id is not null;
create index captures_is_project_idx on public.captures (user_id) where is_project = true;

-- 'serious' removal: in-place migration of any existing rows, then swap the
-- CHECK constraint. Done in this order so we never have a row that violates the
-- new constraint mid-migration.

update public.captures set state = 'developed' where state = 'serious';

alter table public.captures drop constraint if exists captures_state_check;
alter table public.captures add constraint captures_state_check
  check (state in ('raw','developed','archived'));

-- ============================================================
-- 3. RLS for projects (mirrors the captures pattern in §6.2)
-- ============================================================

alter table public.projects enable row level security;

create policy projects_owner on public.projects
  for all to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());
